### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by rogvid** [jasn/regnskaber#1]
There's an error in the fix_namespaces_in_csv function.

The line in which you iterate over columns should be in reverse, or else you'll end up shrinking a list before iterating over said list and this sometimes results in 'IndexError: list index out of range'.

The change suggestion is therefore to change it from
for c in columns:
to 
for c in columns[::-1]:

**Comment by jasn** [comment]
Thanks for letting me know.
I cleaned up the code around there also, so now it should be more readable.
